videos/urls.py
from django.conf.urls import url

from .views import VideoDetail, VideoList, VideoListLatest


urlpatterns = [
    url(r'^$', VideoListLatest.as_view(), name='videos_latest'),
    url(r'^all/$', VideoList.as_view(), name='videos_all'),
    url(r'^(?P<slug>[a-z0-9_-]+).html$', VideoDetail.as_view(), name='videos_detail'),
]

videos/models.py
from __future__ import unicode_literals

import datetime

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from feincms.extensions import ExtensionsMixin


DEFAULT_LATEST_LIMIT = 3


class VideoManager(models.Manager):
    def latest(self, limit=None):
        if limit is None:
            limit = getattr(settings, 'VIDEOS_LATEST_LIMIT', DEFAULT_LATEST_LIMIT)
        return self.get_queryset()[:limit]


@python_2_unicode_compatible
class Video(models.Model, ExtensionsMixin):
    """
    Extensible video model.
    """
    title = models.CharField(max_length=255)
    slug = models.SlugField(
        max_length=127,
        editable=True,
        unique=True,
        help_text=(
            "This will be automatically generated from the title, and " +
            "is used as the video's website address"
        ),
    )
    preview = models.FileField(max_length=255, upload_to='videos/preview', null=True, blank=True, help_text=_('Preview image for this video.'))
    length = models.TimeField(blank=True, null=True, help_text='hh:mm:ss')
    recorded = models.DateField(blank=True, null=True)
    created = models.DateTimeField(editable=False, default=timezone.now)

    objects = VideoManager()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.title

    @property
    def length_display(self):
        raise NotImplementedError('https://github.com/incuna/incuna-videos/issues/8')
        return timesince(datetime.time(0, 0, 0), self.length)

    @classmethod
    def register_extension(cls, register_fn):
        from .admin import VideoAdmin
        register_fn(cls, VideoAdmin)


@python_2_unicode_compatible
class Source(models.Model):
    """
    Video source (inspired by the HTML5 <source> tag)
    """
    TYPE_MP4 = 'video/mp4; codecs="avc1.42E01E, mp4a.40.2"'
    TYPE_WEBM = 'video/webm; codecs="vp8, vorbis"'
    TYPE_OGG = 'video/ogg; codecs="theora, vorbis"'
    TYPE_CHOICES = getattr(settings, 'VIDEO_TYPE_CHOICES', (
        (TYPE_MP4, 'mp4'),
        (TYPE_WEBM, 'webm'),
        (TYPE_OGG, 'ogg'),
    ))
    video = models.ForeignKey(Video, related_name='sources')
    file = models.FileField(upload_to='videos/%Y/%m/')
    type = models.CharField(max_length=255, choices=TYPE_CHOICES)

    def __str__(self):
        return '{video_title} {type}'.format(
            video_title=self.video.title,
            type=self.get_type_display(),
        )

    def get_absolute_url(self):
        return self.file.url

videos/module/chapters/models.py
import datetime

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class Chapter(models.Model):
    """Video section"""
    video = models.ForeignKey('videos.Video', related_name='chapters')
    title = models.CharField(max_length=255)
    timecode = models.TimeField(help_text='hh:mm:ss')
    preview = models.ImageField(upload_to='videos/chapter/', null=True, blank=True, help_text=_('Preview image for this chapter.'))

    class Meta:
        app_label = 'videos'
        ordering = ('timecode',)

    def __str__(self):
        return self.title

    @property
    def seconds(self):
        timecode = self.timecode
        seconds = datetime.timedelta(
            hours=timecode.hour,
            minutes=timecode.minute,
            seconds=timecode.second,
        ).total_seconds()
        return int(seconds)

videos/module/speakers/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Speaker(models.Model):
    """A person who features in a video"""
    name = models.CharField(max_length=127)
    slug = models.SlugField(
        max_length=127,
        help_text=(
            "This will be automatically generated from the name, and is used" +
            "in the speaker's website address",
        ),
        editable=True,
        unique=True,
    )

    class Meta:
        app_label = 'videos'

    def __str__(self):
        return self.name

videos/views.py
from django.views.generic import DetailView, ListView

from .models import Video


class VideoList(ListView):
    template_name = 'videos/list.html'
    model = Video


class VideoListLatest(VideoList):
    def get_queryset(self):
        return Video.objects.latest()


class VideoDetail(DetailView):
    template_name = 'videos/detail.html'
    model = Video

    def get_context_data(self, **kwargs):
        extensions = ('chapters', 'speakers')
        for extension in extensions:
            manager = getattr(self.object, extension, None)
            if manager:
                kwargs.update({extension: manager.all()})
        return super(VideoDetail, self).get_context_data(
            sources=self.object.sources.all(),
            **kwargs
        )

videos/templates/videos/_video.html
{% load imagekit %}


<div class="video-content">
    <h3>{{ video.title }}</h3>

    {% if speakers %}
        <span class="video-speakers">With: <strong>{% for speaker in speakers %}{{ speaker.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</strong></span>
    {% endif %}

    <video controls {% if video.preview %}poster="{{ video.preview.url }}"{% endif %}>
        {% for source in sources %}
            <source src="{{ source.file.url }}" type="{{ source.type }}">
        {% endfor %}

        {% with source=sources|first %}
            <a href="{{ source.file.url }}">
                {% if video.preview %}
                    <img src="{{ video.preview.url }}">
                {% else %}
                    <span>Download video</span>
                {% endif %}
            </a>
        {% endwith %}
        {% if video.captions_file %}
            <track src="{{ video.captions_file.url }}"></track>
        {% endif %}
    </video>

    {% if chapters %}
        <div class="chapters">
            <ul>
                {% for chapter in chapters %}
                    <li><a id="chapter-{{ chapter.pk }}" href="#{{ chapter.seconds }}">{% if chapter.preview %}{% thumbnail "75x56" chapter.preview %}{% endif %}{{ chapter.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</div>

videos/templates/videos/base.html
{% extends "base.html" %}


{% block content %}
    {% block video-nav %}
        <ul id="videos-menu">
            <li>
                <a href="{% url 'videos_latest' %}">Latest videos</a>
                <a href="{% url 'videos_all' %}">View all</a>
            </li>
        </ul>
    {% endblock video-nav %}
    {% block video-content %}{% endblock video-content %}
{% endblock content %}

videos/templates/videos/content/default.html
{% include 'videos/_video.html' with video=video %}

videos/templates/videos/detail.html
{% extends "videos/base.html" %}


{% block video-content %}
    {% include 'videos/_video.html' with video=video %}
{% endblock video-content %}

videos/templates/videos/list.html
{% extends "videos/base.html" %}

{% load thumbnail %}
{% block video-content %}
<ul id="video-list">
    {% for video in video_list %}
    <li>
        {% with chapters=video.chapter_set.all speakers=video.speakers.all %}
        {% url 'videos_detail' slug=video.slug as video_detail_url %}

        {% if video.length %}<span class="video-length"><strong>{{ video.length_display }}</strong></span>{% endif %}
        <h3><a href="{{ video_detail_url }}">{{ video.title }}</a></h3>
        {% if speakers %}<span class="video-speakers">With: <strong>{% for speaker in speakers %}{{ speaker.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</strong></span>{% endif %}
        {% if video.preview %}{% thumbnail video.preview "166x92" as im %}<a class="video-preview" href="{{ video_detail_url }}"><img src="{{ im.url }}" ></a>{% endthumbnail %}{% endif %} 
        {% if chapters %}
        <div class="chapters">
            <ul>
                {% for chapter in chapters %}
                <li><a id="chapter-{{ chapter.pk }}" href="{{ video_detail_url }}#{{ chapter.seconds }}">{{ chapter.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endwith %}
    </li>
    {% endfor %}
</ul>
{% endblock video-content %}